// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.Contexts.HumanCapitalContext;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(HumanCapitalContext))]
    partial class HumanCapitalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Company");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aa329c6c-8bac-4ab7-b4a8-c78edf73ef46"),
                            Address = "5th Settlement",
                            Name = "Deloitte"
                        },
                        new
                        {
                            Id = new Guid("66569d54-aa5a-45d1-8bb9-5ed060878141"),
                            Address = "Helioplios",
                            Name = "LuftBorn"
                        });
                });

            modelBuilder.Entity("Domain.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasMaxLength(60)
                        .HasColumnType("int");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b021659e-12c6-4b2c-aaa2-f73c355a6c59"),
                            Age = 25,
                            CompanyId = new Guid("66569d54-aa5a-45d1-8bb9-5ed060878141"),
                            Name = "Marwan"
                        },
                        new
                        {
                            Id = new Guid("28266870-0b42-4c46-92a9-babb17905ecd"),
                            Age = 31,
                            CompanyId = new Guid("66569d54-aa5a-45d1-8bb9-5ed060878141"),
                            Name = "Mohamed"
                        },
                        new
                        {
                            Id = new Guid("4ebfba95-2575-473d-9287-051a15ed45fd"),
                            Age = 26,
                            CompanyId = new Guid("aa329c6c-8bac-4ab7-b4a8-c78edf73ef46"),
                            Name = "Rahaf"
                        });
                });

            modelBuilder.Entity("Domain.Models.Employee", b =>
                {
                    b.HasOne("Domain.Models.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Domain.Models.Company", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
